---
title: "p8105_hw5_mgw2144"
output: github_document
date: "2023-11-08"
---

```{r message=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = ("viridis"))

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1 


# Problem 2
## Reading the data and creating a dataframe with the map function

```{r message=FALSE, warning=FALSE}
study_data = 
  tibble(
    files = list.files('data/study_data'),
    path = str_c("data/study_data/", files)
  ) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest() 
```

## Tidying the data

```{r}

study_data_tidy = 
  study_data %>% 
  separate(files, into = c("control_arm", "subject_ID", "csv")) %>% 
  mutate(
    control_arm = ifelse(control_arm == "con", "control", control_arm),
    control_arm = ifelse(control_arm == "exp", "experimental", control_arm)
  ) %>% 
  pivot_longer(
    cols = starts_with("week"),
    names_prefix = "week_",
    names_to = "week_number",
    values_to = "observation"
  ) %>% 
  mutate(
     week_number = as.numeric(week_number)) %>% 
  select(control_arm, subject_ID, week_number, observation)

```

## Plotting the tidy data 

## Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

```{r}

study_plot = 
  study_data_tidy %>% 
  ggplot(aes(x = week_number, y = observation, colour = subject_ID)) +
  geom_point() +
  geom_line() +
  facet_grid(.~control_arm) +
  labs(
    x = "Week",
    y = "Observation", 
    title = "Observations by week for each subject in both control arms" 
  )

study_plot

```



# Problem 3 